### ISSUE TITLE
STAR v non-STAR processing confusion

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#142]
https://mailarchive.ietf.org/arch/msg/acme/XF0qZ5Ba2ldx4Dxyuyo6vUV8-FA/

```
Section 2.3.2 says: "Besides, when delegation is for a STAR certificate,
..." (in four places in this section).  I find this part of the document
structure a bit confusing.  Maybe it is the lask ot adequate warning
about support for long-lived certificates.  Maybe it the the mixing of
STAR certificate and long-lived certificate processing in one section.
I suggest that separate sections be used to present STAR certificate and
long-lived certificate processing
```

**Comment by thomas-fossati** [comment]
The confusion Russ is pointing at depends on the relative placement of the sections: If we moved the content of 2.4 somewhere before 2.3.2, we would give enough context to understand the differential pilgrimage of the Order object without the reader sweating too much.

**Comment by thomas-fossati** [comment]
The alternative would be to clone 2.3.2 for non-STAR flows and place it after 2.4

**Comment by yaronf** [comment]
I read it once again. I think 2.3.2 right now is extremely confusing, and the only thing we can do is clone it. But rather than place the clone after 2.4, can we have:
- 2.3.2. Order object... - STAR
- 2.3.3. Order object... - Non-STAR

Then 2.4 can go away, with the material going into either the new 2.3.3 or the "On Cancellation" section which becomes "On Cancellation and Revocation".

**Comment by thomas-fossati** [comment]
> [...] the only thing we can do is clone it. But rather than place the clone after 2.4, can we have:
> 
> * 2.3.2. Order object... - STAR
> * 2.3.3. Order object... - Non-STAR
> 
> Then 2.4 can go away, with the material going into either the new 2.3.3 or the "On Cancellation" section which becomes "On Cancellation and Revocation".

LGTM, I'll give it a try.
