### ISSUE TITLE
Cite RFC 8996

### ISSUE THREAD

**Issue by yaronf** [yaronf/I-D#255]
For deprecation of TLS 1.0, 1.1 (note this is part of BCP195)

**Comment by yaronf** [comment]
Also, should our draft "deprecate" it, like it does RFC 7525?

**Comment by yaronf** [comment]
Discussion: for now, cite.

In the future, discuss with the RFC Ed team on whether 8996 should be dropped from BCP195 since it's not really needed once bis is published.

**Comment by yaronf** [comment]
The "cite" part is addressed by #258.

**Comment by stpeter** [comment]
I talked with the RFC Editor team. Deprecating (or, to be precise, obsoleting) RFC 8996 would be tricky because we want to deprecate Section 6 only, and even that is a case of Section 6 being unnecessary once 7525bis is an RFC (it's the same text, after all) - we don't want to obsolete all of RFC 8996. What we're really seeking it to remove RFC 8996 from BCP 195 once 7525bis is an RFC, but it appears we don't have good precedent for that. I suspect it would be more trouble than it's worth to pursue this cleanup task with the area directors, so we might need to live with RFC 8996 being part of BCP 195. This isn't horrible because no longer supporting TLS 1.0 and TLS 1.1 is in fact a best practice for the secure use of TLS.

**Comment by yaronf** [comment]
Makes sense. Thanks @stpeter. Closing the issue.
