### ISSUE TITLE
recommendations around strict TLS config vs upgrade 

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#311]
_"In cases where an application protocol allows implementations or deployments a choice between strict TLS configuration and dynamic upgrade from unencrypted to TLS-protected traffic (such as STARTTLS), clients and servers SHOULD prefer strict TLS configuration."_

* First of all, why is this a SHOULD and not a MUST? Especially since "prefer" seems to also weaken this already.
* And second, does prefer mean a fallback to dynamic upgrade is allowed if a strict configuration fails? If so, does that apply to all kind of failures? Is this not introducing a downgrade attack?

_"A client SHOULD attempt to negotiate TLS even if these indications are not communicated by the server."_

* Again, why a SHOULD and not a MUST ? I guess this is why the above uses "prefer" or else there would be a contradiction.

**Comment by yaronf** [comment]
This is original text from RFC 7525. But let's open this discussion on the list.

**Comment by stpeter** [comment]
Personally, I would find "MUST" acceptable here.

How many application protocols provide a choice between strict TLS configuration and dynamic upgrade? (I know that years ago the IESG preferred dynamic upgrade, likely as a way to conserve ports, but it's unclear to me how many application protocols use *both* methods and give implementations a choice.)

**Comment by yaronf** [comment]
@stpeter And what about fallback? Maybe add: "The words "strict configuration" imply that automated fallback to dynamic configuration is not allowed" - or something to that effect.

**Comment by stpeter** [comment]
I suppose that "strict configuration" could mean two different things:

(1) Always connect "securely" (e.g., TLS with appropriate cipher suites, proper certificate checking, etc.); this outcome that could result from using a TLS-only port or a port that supports either a plaintext connection or, via dynamic upgrade, a TLS connection.

or

(2) Connect only at TLS-only ports and refuse to use dynamic upgrade mechanisms (primarily STARTTLS) because of concerns over downgrade attacks.

I'm not sure how the term is typically use.

**Comment by stpeter** [comment]
I will rewrite this text.

**Comment by stpeter** [comment]
> > I suppose that "strict configuration" could mean two different things:
> > (1) Always connect "securely" (e.g., TLS with appropriate cipher suites, proper certificate checking, etc.); this outcome could result from using a TLS-only port or a port that supports either a plaintext connection or, via dynamic upgrade, a TLS connection.
> 
> The assumption here is that the security properties provided by establishing a TLS channel "directly" are the same as those you'd get from dynamic upgrade, i.e., there is no possible security / privacy degradation when falling back to the latter.

If local policy at the client is to not accept an unencrypted connection, then I'm not convinced that the _method_ of achieving TLS protection truly matters (TLS-only port vs. dynamic upgrade via STARTTLS).

**Comment by thomas-fossati** [comment]
I didn't know this was the background :-)

To me (newbie), the goal of the policy recommendation looks like:
_"you SHALL use the best security your protocol has to offer, and you MUST NOT fall back to less secure options"_
where the ideal order is:
1. strict
2. upgrade
3. clear-text

So, for example, if your protocol supports only upgrade then you will use upgrade and refuse to fall back to clear-text.  If your protocol supports strict and upgrade and clear-text, you will use strict and never fall back to upgrade or clear-text, etc.

**Comment by thomas-fossati** [comment]
> If local policy at the client is to not accept an unencrypted connection, then I'm not convinced that the _method_ of achieving TLS protection truly matters (TLS-only port vs. dynamic upgrade via STARTTLS).

nice; I see this from the opposite angle apparently.  To me the policy in this case is one that accepts fall-back to upgrade (i.e., to a less secure but still good enough for my threat model).

So, to support your case I think I can modify my previous statement as follows:

_"you SHALL use the best security your protocol has to offer, and you SHOULD NOT fall back to less secure options, unless allowed by local policy"_

**Comment by stpeter** [comment]
> I didn't know this was the background :-)
> 
> To me (newbie), the goal of the policy recommendation looks like: _"you SHALL use the best security your protocol has to offer, and you MUST NOT fall back to less secure options"_ where the ideal order is:
> 
>     1. strict
> 
>     2. upgrade
> 
>     3. clear-text
> 
> 
> So, for example, if your protocol supports only upgrade then you will use upgrade and refuse to fall back to clear-text. If your protocol supports strict and upgrade and clear-text, you will use strict and never fall back to upgrade or clear-text, etc.

Maybe. :-) There are a few wrinkles. To me, the main one is that in some protocols (I keep using the example of XMPP because that is what I know best) the official protocol approved by the IETF only allows STARTTLS, but unofficially some clients and servers keep using the TLS-only ports (for client-to-server communications that is 5223 instead of the official 5222). Now will 7525bis recommend that clients use an unsanctioned port and thereby violate the "agreement" that the community reached with the IESG back in 2004? We could inadvertently open a can of worms...

**Comment by stpeter** [comment]
Furthermore, is it provably insecure to use an upgrade mechanism like STARTTLS if local policy mandates never falling back to cleartext? Or are we just worried because dynamic upgrade mechanisms feel less clean?

**Comment by yaronf** [comment]
Starting with Peter's latest text, highlighting the text we discuss below:

> Many existing application protocols were designed before the use of TLS became common. These protocols typically support TLS in one of two ways: either via a separate port for TLS-only communication (e.g., port 443 for HTTPS) or via a method for dynamically upgrading a channel from unencrypted to TLS-protected (such as STARTTLS, which is used in protocols such as SMTP and XMPP). Because dynamic upgrade methods depend on negotiations that begin over an unencrypted channel (e.g., the server might send a flag indicating that TLS is required), they are subject to downgrade attacks; nevertheless, **a client SHOULD attempt to negotiate TLS even if these indications are not communicated by the server**. In any case, whether the mechanism for protecting the communication channel is a TLS-only port or a dynamic upgrade method, what matters is the end state of the channel. **In general, clients and servers SHOULD prefer to negotiate TLS and as a matter of local policy ought to be configured by default to require TLS wherever possible.**

Question to Peter: instead of telling the client to negotiate even if the server indication is missing, shouldn't we simply say, the client aborts the connection if the indication is missing and also aborts the connection if the TLS handshake fails? - To some degree the answer depends on protocol/implementation quirks. WDYT?

Proposed replacement for the last sentence:

When TLS-only communication is available for a certain protocol, it MUST be used by implementations and MUST be configured by administrators. When a protocol only supports dynamic upgrade, implementations MUST enable a strict local policy (a policy that forbids fallback to plaintext) and administrators MUST use this policy.

**Comment by stpeter** [comment]
Thanks for working on this text.

The proposed last sentence looks good.

You are right that it's better to abort the connection. This is _likely_ consistent with the relevant protocol specification (e.g., if there's no indication that the server supports or requires TLS and the client is configured to only connect via TLS then the client can't do anything but abort the connection).

**Comment by stpeter** [comment]
See https://github.com/yaronf/I-D/pull/348/commits/aa1e9ad6c2c67f521563b846a82bfc35fb929de2

**Comment by yaronf** [comment]
Oops, keeping the issue open: we need to add this change to the list of changes from 7525.
