### ISSUE TITLE
greenfield deployments, not protocols

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#320]
_"Implementations of "greenfield" protocols or deployments, where there is no need to support legacy endpoints"_

* I don't think "protocols" applies here. It really just says "if you are a greenfield deployment (you manage all the nodes communicating), you could insist on TLS 1.3 only."

**Comment by stpeter** [comment]
I think "protocols" is fine (because there is such a thing as a newly developed protocol, implementations of which don't need to worry about backward compatibility with legacy endpoints), but our wording is somewhat ambiguous because there is no such thing as "implementations of 'greenfield' ... deployments". Everything else in Section 3.1.1 is about implementations, so I suggest:

>    Implementations of newly-developed protocols SHOULD support TLS 1.3 only with no negotiation of earlier versions, since there is no need to allow legacy endpoints that support TLS 1.2.

**Comment by yaronf** [comment]
Do we really want a normative SHOULD?

**Comment by stpeter** [comment]
Good point. The primary audience for this document consists of those who implement and deploy TLS-based technologies - not protocol developers. Probably any advise that we provide to protocol developers ought to use non-normative wording.

**Comment by yaronf** [comment]
Wait, we now got it the wrong way around! We have 2 issues referring to the same paragraph, let me complete the PR and please review it. Spoiler: first should is normative, 2nd should is non-normative.
