### ISSUE TITLE
Section 3.1.1 what about SSLv1

### ISSUE THREAD

**Issue by thomas-fossati** [yaronf/I-D#419]
_Comment by @evyncke_

While I am not familiar with old SSL, if there was a SSLv1, should this document also have recommendation about SSLv1 ?

**Comment by thomas-fossati** [comment]
We say nothing about SSL 1.0 since it was never publicly released.  The first version that got deployed was 2.0.

**Comment by evyncke** [comment]
Fair enough ;-)

From: Thomas Fossati ***@***.***>
Reply to: yaronf/I-D ***@***.***>
Date: Tuesday, 12 July 2022 at 22:48
To: yaronf/I-D ***@***.***>
Cc: Eric Vyncke ***@***.***>, Mention ***@***.***>
Subject: Re: [yaronf/I-D] Section 3.1.1 what about SSLv1 (Issue #419)


We say nothing about SSL 1.0 since it was never publicly released. The first version that got deployed was 2.0.
