### ISSUE TITLE
change 1.3 from SHOULD support to MUST support?

### ISSUE THREAD

**Issue by stpeter** [yaronf/I-D#446]
In his secdir review, Benjamin Kaduk seems to suggest that we make the following change:

OLD

   *  Implementations SHOULD support TLS 1.3 [RFC8446] and, if
      implemented, MUST prefer to negotiate TLS 1.3 over earlier
      versions of TLS.

NEW

   *  Implementations MUST support TLS 1.3 [RFC8446] and MUST
      prefer to negotiate TLS 1.3 over earlier versions of TLS.

cc @kaduk

**Comment by stpeter** [comment]
@thomas-fossati Um, yes. I was typing faster than I was thinking. ;-)

**Comment by kaduk** [comment]
While I think this proposal is reasonable BCP guidance in 2022, I don't think it's actually what I intended to suggest.  If we think we have consensus for this, that's great, and we should ignore the rest of what I am about to write here.  If, however, we run into trouble, especially trying to make this change late in the process, we might want to rethink whether TLS 1.2 is really "MUST implement".  Something more nuanced (and hard to express) like "SHOULD implement 1.2, SHOULD implement 1.3, MUST implement at least one, also there are interop concerns if you only implement one and there's an existing protocol+deployment" might garner a broader pool of support.  But since nuance is easy to miss as the reader anyway, maybe the short and simple "MUST 1.3" actually is better.

**Comment by stpeter** [comment]
@kaduk Thinking about this further, I'd prefer to avoid complex or nuanced text. Personally I'd be comfortable with "MUST 1.3" (but note that Thomas and I haven't had a chance to talk about this with Yaron yet). However, that will likely require a third WGLC and second IETF LC. We'd need to confer with @paulwouters to figure out the path forward.

**Comment by yaronf** [comment]
For the record, I disagree with "MUST 1.3". When we published RFC 7525, there were strong security justifications to our reasonably onerous recommendations. Now I don't see a similar justification.

If we add "MUST 1.3", enterprises like my own will need to go into expensive make-sure-everything-supports-1.3 programs. I don't think I'll be able to explain internally why thins makes sense.

Lastly, I don't see consensus on the list for this. On the contrary, I see consensus against.

**Comment by stpeter** [comment]
I agree on the lack of consensus. Closing.
